"use client"
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { useRouter } from "next/navigation";
import Navbar from "@/component/NavBar";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const router = useRouter()
    useEffect(()=>{
      const accessToken:string | null = localStorage.getItem("accessToken")
      if(!accessToken){
        router.push("/login")
      }
    },[])
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppRouterCacheProvider>
        {/* <Navbar/> */}
        {children}
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
